### ISSUE TITLE
iOS 15 - ionic app geolocation permission prompt message showing ionic://localhost

### ISSUE THREAD

**Issue by Sagar-Khenat** [apache/cordova-plugin-geolocation#242] opened 2021-11-26 09:32 UTC
# Bug Report

## Problem
Getting "ionic://localhost" in location prompt message on iOS 15.

### What is expected to happen?
"ionic://localhost" should be replaced with App name.

### What does actually happen?
Getting permission app name empty in iOS 15 with "ionic://localhost"

## Information

Install cordova-plugin-geolocation plugin and call the getCurrentPosition method to get users location in IOS 15.

### Environment, Platform, Device
IOS 15 platform .
"cordova-plugin-geolocation": "^4.1.0"

### Additional Information

Need your support to fix the below issue.

In my app, I am using geolocation plugin to get users location. When the plugin asks for getting user's current permission using getCurrentPosition() method, we are seeing “ionic://localhost” in header.

Have shared screenshot below :

![image](https://user-images.githubusercontent.com/65883219/143558895-67bd3023-aa58-4bd6-ba88-f5bc75f299ab.png)

It would be useful to add at least the app name in the location prompt permission dialogue. This prompt is seen only while updating existing app version on iOS 15 or later. It is not seen on other iOS versions.

Requesting plugin maintainers to kindly look into this scenario. 
Any kind of help or workaround for this will be very helpful.

**Comment by geshub** [comment] 2021-12-16 10:03
It's already discussed here [https://github.com/apache/cordova-plugin-geolocation/issues/240], but no solution for now.

**Comment by jcesarmobile** [comment] 2022-06-02 10:02
Closing as duplicate of #240

**Closed by jcesarmobile** 2022-06-02 10:02 UTC
