### ISSUE TITLE
IOS 15 Geolocation permission message issue.

### ISSUE THREAD

**Issue by chandelkushaltesting** [apache/cordova-plugin-geolocation#240] opened 2021-10-01 08:54 UTC
# Bug Report

Hi Team,

We faced a strange issue with iOS 15, whenever we are calling the getCurrentPosition() method then on permission header. We are getting app name empty "" with "://" .

Please find the screenshot below.

![2021-10-01](https://user-images.githubusercontent.com/80328136/135592498-4d3053d0-76a2-4400-8740-8f7c6b01ff4c.png)

## Problem

Getting permission app name empty in iOS 15 with "://" 

### What is expected to happen?

 "://"  should be replaced with App name.

### What does actually happen?

Getting permission app name empty in iOS 15 with "://" 

## Information

Install the above plugin and just call the getCurrentPosition method you able to reproduce the issue in  IOS 15.

### Environment, Platform, Device

IOS 15 platform .
"cordova-plugin-geolocation": "^4.1.0",
"@ionic-native/geolocation": "^5.36.0",

## Checklist

- [ ] I searched for existing GitHub issues YES
- [ ] I updated all Cordova tooling to most recent version YES
- [ ] I included all the necessary information above YES

**Comment by Sagar-Khenat** [comment] 2021-11-19 09:37
Are you able to find a fix for this issue, related to location permission prompt? Or are the plugin maintainers going to make updates for this plugin, as we are also seeing this permission prompt in our app.

**Comment by geshub** [comment] 2021-11-30 10:24
Does anyone found any solution to hide that prompt on IOS 15 ?

**Comment by programadormartinez** [comment] 2022-02-04 14:03
Day 4 feb, not solutions.

**Comment by geshub** [comment] 2022-02-04 14:49
@programadormartinez on my Ionic app, I solved it putting each calls of navigator.geolocation inside $ionicPlatform.ready(function() {}) to be sure the plugin is called and not the html5 location api. 
Should be the same with `deviceready` event if not on Ionic.
But I don't know why the previous code had no popup on IOS 14.

**Comment by programadormartinez** [comment] 2022-02-04 15:16
> @programadormartinez on my Ionic app, I solved it putting each calls of navigator.geolocation inside $ionicPlatform.ready(function() {}) to be sure the plugin is called and not the html5 location api. Should be the same with `deviceready` event if not on Ionic. But I don't know why the previous code had no popup on IOS 14.

how to apply changes? I'm not sure where to make the changes since I don't call that function navigator.geolocation anywhere

**Comment by geshub** [comment] 2022-02-04 15:25
@programadormartinez You're supposed to use this function navigator.geolocation.getCurrentPosition with this plugin

**Comment by programadormartinez** [comment] 2022-02-04 17:29
Solution:  this.ptf.ready().then(()=> {
        GET LOCATION HERE
        //this.getGeo();
      })

**Comment by filipRisteski** [comment] 2022-05-03 22:22
This is not the solution. Do we have a real solution for this problem?

**Comment by breautek** [comment] 2022-05-03 22:53
If you're seeing `://` as the title, it's likely because you're calling on the browser's implementation of geolocation rather than the cordova plugins implementation. This can occur when you have invoked the geolocation APIs **before** the `deviceReady` event has fired.

If you are waiting for the `deviceReady` and still is seeing this issue, we'll need a reproduction app to move this forward. In such case, please reduce the amount of dependencies down to the bare minimum, e.g. no frameworks.

**Comment by jcesarmobile** [comment] 2022-09-25 14:25
Closing since no reproduction has been provided and I can’t reproduce.
It’s probably related to the plugin not being correctly installed or using it before device ready, in both cases it would use the web geolocation that has this prompt.

**Closed by jcesarmobile** 2022-09-25 14:25 UTC
