### ISSUE TITLE
Timeout exception Android 8+9 (v2.4.3), Android 8 (v4.0.1)

### ISSUE THREAD

**Issue by ghost** [apache/cordova-plugin-geolocation#110] opened 2018-08-20 10:29 UTC
I got timeout exception when try to get location. I have no errors with previous android versions.

**Comment by janpio** [comment] 2018-08-20 10:41
So you think there is a new bug/problem with Android 9?
Is this reproducible on different devices?
What is the minimal code to reproduce this behaviour?

**Comment by llinaresvicent** [comment] 2018-08-20 10:56
Yes, I think it's a problem with Android 9 because the app has been tested with other versions of android without problems. I tried with an emulator and physical device (pixel).

**Comment by crapthings** [comment] 2018-08-21 02:15
same here to
android 7 
android 8

**Comment by llinaresvicent** [comment] 2018-08-21 08:28
@janpio "yes". It's broken the last version of the plugin (2.4.3) for Android 8 and for Android 9. Trying to fix it for my project I installed older versions of the plugin and it worked with 2.1.0 version for Android 8 but not for 9.  Look at "Edit:" on last line.

**Comment by janpio** [comment] 2018-08-21 08:30
I changed the title to reflect that.

**Comment by llinaresvicent** [comment] 2018-08-21 09:02
Ok, after testing on other devices and with an app that only takes your location  I can confirm the plugin works on Android 9 too but with 2.1.0 version. I think the issue should remain still opened because it doesn't work properly on the last version. @crapthings, check if works for you with 2.1.0 version.

**Comment by SimonSoft93** [comment] 2018-08-21 16:10
Hi,
I've the same issue.
Cordova: 8.0.0
Android platform: 6.4.0
I tried many times with all configs and all time i get Timeout exception on 2 devices with Android 6 and 7.
I tried with latest version (4.0.1) and with 2.4.3 version but i still get the error

**Comment by Arxi** [comment] 2018-08-24 13:50
I have:
android 8.0.0
cordova 8.0.0
cordova-android 6.4.0

plugin settings:
timeout: 30000
maximumAge: 39600000
highAccuracy: true or false, tried both

I have tried this plugin in versions 4.0.1, 2.4.3 and 2.1.0 and I almost always get timeout. Only if I run some other app, like GPS Status, and then wait for a long time, I can get a reading in my app. I'm not quite able to reproduce this success.

For certain reasons, I don't want to upgrade cordova-android, even though I have run out of options, so I might be forced to try that.

**Comment by janpio** [comment] 2018-08-24 13:53
Definitely try that @Arxi, even if just to confirm if the problem goes away or not. Then you know what the reason is.

**Comment by Arxi** [comment] 2018-08-24 14:11
Okay, I'll try. In the meantime, I tried using the version 0.3.6 of this plugin, and I can confirm that works (all other variables staying the same).

**Comment by janpio** [comment] 2018-08-24 14:14
For real? That version is from Feb 6, 20**14**...

**Comment by Arxi** [comment] 2018-08-24 14:30
Yeah, for real :) though I guess other problems would come up with that version (permissions and stuff), so I'm of course reluctant to use that.

**Comment by und3f1n3d** [comment] 2018-09-10 18:06
So unsure what has changed in the Android patch, but here are my findings:

Tried with Samsung S7 with 8.0 Android, latest security patch and also Samsung S8 (8.0 Android), using v2.4.3 and as well as v4.0.1 of the plugin.

Samsung S7 works regardless no matter which version of the plugin.
Samsung S8 stopped working suddenly regardless of which version of the plugin.

Passed in enableHighAccurancy: true, didn't help on Samsung S8.

Then, checked both devices settings,  Connection > Locating Methods , both have already selected 'High accuracy'.

Then on Samsung S8, I selected 'Phone Only'.  Still the plugin does not work for Samsung S8. 
So I reselected 'High accuracy'.  Then as soon as I pressed 'Agree' on the 'Improve Location accuracy' prompt screen, the plugin works.   It seems like there are some sort of permission changes in the latest patch...?!?!

**Comment by vpedrosa** [comment] 2018-10-11 16:03
Experiencing crashes in app on Oneplus6@Android 9 and AVD 8.1 Android simulation

**Comment by seb2086** [comment] 2018-10-20 16:12
Hello,

Same problem here, it's works fine on iOS and Android < 8.0.0.
I use cordova-plugin-geolocation v2.4.3.

A patch is planned quickly for this bug ?

Thanks.

**Comment by rosbal** [comment] 2018-10-23 15:48
Any updates on this issue? I am facing the timeout issue in Android 8.1. Is there any workaround for this?

**Comment by seb2086** [comment] 2018-10-23 22:06
I found a workaround using plugin https://github.com/Esri/cordova-plugin-advanced-geolocation.
It's only compatible with Android but, in my case,  it works very fine ;)

**Comment by carlo318** [comment] 2018-11-09 09:37
Same problem here, with Android 8.0.0. Not working neither with v.2.4.3 nor with 4.0.1.
I tried also cordova-plugin-advanced-geolocation but inside a building it gives no info for gps, and network gives geolocation, but with very low accuracy  (more than 10k meters). Maybe it's normal with wifi.
Device: Asus Zenfone 3.

**Comment by cimoskill** [comment] 2019-01-09 15:18
I confirm from my tests that there is no way to make it work as we expect.
I made an Application in production that uses the geolocation as main feature.
My phone is a Samsung A3 with Android 8 and I found that a way to "make it work again" is to go to the location settings of the phone and change the option of accuracy:
I had "only phone" (so via gps only) and there is no way to make it work.
**I changed it to "high accuracy" (don't know if it's the right name cause it is translated) and now it works again....**
I think that cordova-plugin-geolocation should be improved with some new google api in the android native code in order to fit and manage these options.
Anyway this is a big issue now, I read about moving to other plugins but the issue remain.
I don't have the time to study in deep now this part but I'm pretty sure the solutions is near that point.
Sorry for my bad english.

**Comment by breautek** [comment] 2020-08-14 00:31
> I had "only phone" (so via gps only) and there is no way to make it work.

If the phone is set GPS only, this means the only source of GPS information it can use is from GPS satellites. Cold booting the GPS hardware takes a very long time. It isn't abnormal for this to take >= 15 minutes before you start receiving GPS updates. 

When the phone is set to high accuracy (not to be confused with the API's `highAccuracy` flag), it uses more sources of information such as cellular towers and wifi networks to receive GPS events faster.

Unfortunately this is a user setting that is not configurable by the app.

I have this better explained in my [gist](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e).

I don't believe this is an issue that Cordova can resolve. As was discovered, the issue persisted even when using the native geolocation APIs. So I'll be closing this ticket.

**Closed by breautek** 2020-08-14 00:31 UTC
Labels: platform: android, support, topic: Android 8+

**Comment by spinninghamster** [comment] 2020-12-07 05:12
Could this issue be due to Huawei not supporting Play Services anymore? And instead moving to their own services? See:

https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Guides/introduction-0000001050140246
