### ISSUE TITLE
ios kclerrordomain error 0 & not accurate location

### ISSUE THREAD

**Issue by mohamedmaher2021** [apache/cordova-plugin-geolocation#278] opened 2024-06-28 12:12 UTC
# Bug Report

## Problem
the plugin return kclerrordomain error 0 for ios and sometimes not accurate location after upgarde ios to 17.5.1

### What is expected to happen?
It should return location without any error and high accurate

### What does actually happen?
most of devices updated to ios 17.5.1 retrun kclerrordomain error 0 or not accurate location

### Command or Code

navigator.geolocation.getCurrentPosition(
                                function (position) {
                                
                                    });
                                }, function (error) {
                              
                                    logErrorMessage('code: ' + error.code + '\n' + 'message: ' + error.message + '\n');
                                    if (error.message)
                                        alert(error.message)
                                    else {
                                        if (error.code == 1)
                                            alert('Location Permission Denied');
                                    }
                                },
                                { maximumAge: 0, enableHighAccuracy: true, timeout: 120000 }
                            );

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment] 2024-06-28 13:08
Closing as not a bug.

"not accurate" is an acceptable response from the geolocation API. High accuracy is never guaranteed and the accuracy depends on several factors that out of control of the developer.

It's the app's responsibility to check the `accuracy` field to determine if the given GPS point is accurate enough for their use case. On most devices with a healthy link with 3 or more GPS satellites will give an accuracy reading of 5m, assuming best case environment scenario. Often they will be more like 10m, sometimes 20m. The accuracy field is a measurement with 95% confidence that the true location is within the accuracy reading radius in meters. I've written about this in greater detail [here](https://breautek.com/articles/geolocation-accuracy.html)

> most of devices updated to ios 17.5.1 retrun kclerrordomain error 0

I'm not completely sure what you mean by this, but I'm assuming you mean that you're device is entering the fail delegate:

https://github.com/apache/cordova-plugin-geolocation/blob/543fff401611cc36681d45bd9c25aa43619d93fc/src/ios/CDVLocation.m#L337

Code 0 is:

```
kCLErrorLocationUnknown  = 0,         // location is currently unknown, but CL will keep trying
```

This generally means the GPS receiver in the device does not have any fixes on enough satellites, nor are there any known local cellular towers that hints on your location. As the result, geolocation is not known at this time. The underlying GPS API will continue to triangulate the device position and connect to GPS satellites but the `getCurrentPosition` API only looks at the first response back from the underlying GPS API, which sounds like in your case is this error. If you wanted to try again, then you would have to call `getCurrentPosition` again, though honestly it might be easier to use the watch API instead until you get an acceptable geolocation point, then stop watching.

One last thing, if you're device is unable to make use of any "A-GPS" ([Assisted GPS](https://novotech.com/gnss-gps-antenna-glossary/assisted-gps-a-gps/#:~:text=My%20Cart-,What%20is%20Assisted%20GPS%20(A%2DGPS)%20and%20Its%20Impact,and%20more%20accurate%20location%20tracking.) features and instead is relying solely on GPS satellites, it can take upwards of 10-15 minutes before a device can get a "fix" to 3 or more satellites. A minimum of 3 is required to provide GPS data.

I hope this information helps but I'm closing this ticket because I do not believe this is a bug with the plugin.

**Closed by breautek** 2024-06-28 13:08 UTC
