### ISSUE TITLE
Android   Error : Only secure origins are allowed error

### ISSUE THREAD

**Issue by jcms2018** [apache/cordova-plugin-geolocation#123] opened 2018-11-29 15:01 UTC
Hi, the geolocation is not working on android, I always get the same message, using ionicdevapp + ionic serve -c and also ionic cordova run android on an android device, everything works well on IOS, some idea of how to solve the problem? I have read some forums but it is not clear to me if there is any solution.

Example code :

```
getPosition():any{
var options = {
enableHighAccuracy: true,
timeout: 5000,
maximumAge: 0
};

this.geolocation.getCurrentPosition(options).then(response => {
  console.log('OK'); 
  

})
.catch(error =>{
  console.log("Error="+ error.code +" =>"+ error.message);
})
}
```

Error=1
Only secure origins are allowed (see: https ://goo.gl/Y0ZkNV).

```
Ionic:

ionic (Ionic CLI) : 4.2.1 (/usr/local/lib/node_modules/ionic)
Ionic Framework : ionic-angular 3.9.2
@ionic/app-scripts : 3.2.0

Cordova:

cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
Cordova Platforms : android 7.1.4
Cordova Plugins : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 12 other plugins)

System:

Android SDK Tools : 26.1.1 (/usr/local/Android/Sdk/)
NodeJS : v8.10.0 (/usr/bin/node)
npm : not installed
OS : Linux 4.15

**Comment by janpio** [comment] 2018-11-29 17:21
What version of Android are you testing on?
What device?

**Comment by jcesarmobile** [comment] 2018-12-19 11:48
The problem is ionic dev app as it uses http.
I think https is now supported on ionic CLI, but not sure if that's compatible with dev app.

Anyway, it's not related to the plugin, closing.

**Closed by jcesarmobile** 2018-12-19 11:48 UTC
Labels: platform: android, support

**Comment by Ghayyas** [comment] 2018-12-20 15:03
So how can we get the geolcation?

**Comment by jcesarmobile** [comment] 2018-12-20 15:09
Using https or not using dev app

**Comment by Ghayyas** [comment] 2018-12-20 15:17
Im using ionic how can i use https in ionic ??

**Comment by matrikR** [comment] 2019-01-22 10:06
`ionic cordova run android -l --ssl --debug`
--ssl -> generating ssl for livereload mode :)

**Comment by Jakasha** [comment] 2019-11-27 13:57
The problem is that the default web view scheme for Android is: http://localhost
The geolocation plugin does not accept "http://..." as origin for position requests.
On iOS it works because the default scheme is ionic://localhost

Set the Android Scheme to "https" in the config.xml file:
`<preference name="Scheme" value="https" />`

NB: it is necessary to allow also the navigation for the new scheme:
`<allow-navigation href="https://*"/>`

Other web view configurations:
https://github.com/ionic-team/cordova-plugin-ionic-webview
