### ISSUE TITLE
Unbale to get exact current Location

### ISSUE THREAD

**Issue by InduMeark** [apache/cordova-plugin-geolocation#219] opened 2020-12-18 10:14 UTC
Unable to get an exact current location using this plugin. Getting the location which is 2 to 5kms away from my current location.

### What is expected to happen?

Expectation: Exact Current latitude and longitude.

### What does actually happen?

Getting the location which is 2 to 5kms away from my current location.

## Information
Added options:
{ maximumAge: 3000, timeout: 5000, enableHighAccuracy: true };
Still not getting Correct location

### Command or Code
navigator.geolocation.getCurrentPosition(onSuccess, onError);

### Environment, Platform, Device
Getting the same issue in all android devices.

### Version information
"devDependencies": {
    "cordova-android": "^9.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-plugin-geolocation": "^4.1.0",
    "cordova-plugin-whitelist": "^1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-geolocation": {
        "GPS_REQUIRED": "true"
      }
    },
  }

**Comment by breautek** [comment] 2020-12-18 13:41
There are several environmental reasons outside of the developer's control that may cause poor `accuracy` readings.

Things that tend to cause poor accuracy readings includes being in an office building or any other large building with thick materials, being surrounded by mountains or just poor weather. The "perfect" environment for GPS is being in an open field with clear open skies. Most modern phones can get up to 3 to 5 meters in accuracy; that is, the phone is 95% confident that the actual GPS point is within a 3-5 meters radius of the given location.

I've written a [blog post](https://breautek.com/2020/08/25/geolocation-accuracy/) that goes into more detail but to summarise, you can do the following things to help ensure you have good accuracy reading:

1. Enable `enableHighAccuracy` option (Which I see you've already done).
2. Most devices has Location Accuracy settings on the device itself, which includes enabling A-GPS features like using Wifi / Bluetooth. Enable these settings. Unfortunately this is something you can't programmatically control. You can however use the [diagnostics](https://github.com/dpa99c/cordova-diagnostic-plugin#getlocationmode) plugin to check the current values of these settings and give proper feedback to your users if this is critical for your app.
3. Consider trying to test your app outside if you're in an office building. I also receive poor accuracy in my office building, which is an old think concrete building. Therefore if I'm trying to test a "good accuracy" path, I physically need to take the phone outside.
4. Lastly, this is mostly for android devices - remember that GPS receivers are not standardised by Google. Device manufacturers have the freedom to put whatever GPS receiver they wish if any at all. Cheap budget phones tend to have cheap hardware and a higher tendency to produce poor accuracy readings.

I'm closing this as a "not a bug" issue.

**Closed by breautek** 2020-12-18 13:41 UTC
