### ISSUE TITLE
iOS watchPosition problem 

### ISSUE THREAD

**Issue by ironbone** [apache/cordova-plugin-geolocation#151] opened 2019-04-21 17:03 UTC
# Bug Report

## Problem
The function in subscribe in watchPosition is not called when the user does not touch the screen (or interact with the application) even if the position has changed

### What is expected to happen?
Every time when the position has changed the function should be called.

### What does actually happen?
When subscribing to  the watchPosition the  event function is first called 2-3 times. Then during the application stay in the foreground the event function is not called. There are no errors.

When the user touch the screen (sometimes) the function is called. Every time when the application goes to background and return to the foreground the function is called.

### Environment, Platform, Device

iOS 12.1

### Version information

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   Android SDK Tools : 25.2.5 (/Applications/android-sdks)
   ios-sim           : 7.0.0
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125

Code written in Ionic 4.
```
this.watch = this.geolocation.watchPosition();
this.watch.subscribe(
            (data) => {
                console.log("In watchPosition");
                console.log(data);
                this.data = data;
            },
            (error) => {
                console.log('Error watching location', error)
            }, 
            {
                maximumAge: 3000,
                timeout: 1000,
                enableHighAccuracy: true
            }
        );
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by SandroMoretti** [comment] 2019-05-09 12:23
Hi @ironbone .
Off this issue, when you iphone ask to track localization, a popup message appears?
In my case, a ugly popup appears with content: "/var/containers/Bundle/Application/<<iphone_id>>/App/www/index.html wold like to use your current location"

This is very ugly to users. I just want to know if is my current installation, or everybody that use this plugin in iphone have the same issue.
Sorry for the off topic. Thanks.

**Comment by breautek** [comment] 2019-05-09 12:54
> Hi @ironbone .
> Off this issue, when you iphone ask to track localization, a popup message appears?
> In my case, a ugly popup appears with content: "/var/containers/Bundle/Application/<<iphone_id>>/App/www/index.html wold like to use your current location"
> 
> This is very ugly to users. I just want to know if is my current installation, or everybody that use this plugin in iphone have the same issue.
> Sorry for the off topic. Thanks.

You should open up a new issue to keep things organised. If others are having the same issue, they'll have an easier time finding it (and perhaps contribute). Adding off-topic messages to other issues will negatively affect search engines from indexing pages properly.

**Comment by bitboxfw** [comment] 2019-05-20 13:47
I'm having exact the same problem with the same versions on iOS. Did anyone find a solution for the problem?

**Comment by breautek** [comment] 2019-10-12 02:45
I've created a gist that covers the top reasons why you may not receive GPS results in a timely fashion which can be read [here](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e)

Note that iOS on a cold-start will fire a few GPS points immediately regardless of how accurate or inaccurate the GPS points are, which explains "called 2-3 times."

**Comment by ValentinoRossi1** [comment] 2020-01-01 13:35
I have the same issue. Did anyone already find a solution or workaround for this?

**Comment by breautek** [comment] 2020-01-01 14:11
Couple of notes on why you may not be seeing gpa updates

1. Your in a poor environment, such as in a large office building or basement.
2. Ios implements a distance filter, which I believe Cordova hardcodes to 5 meters when in high accuracy mode (10 meters otherwise if memory serves me right). Therefore you have to be actually moving to receive gps updates, at least 5-10 meters approximately before ios will propagate gps events.

**Comment by ValentinoRossi1** [comment] 2020-01-01 14:20
Thanks for your fast response. I checked both of your points. But unfortunately it still wont work. I tested it on both iPhone and iPad with iOS 13.3.

It seems like iOS stops updating the geolocation after 2-5 seconds. Also the status bar GPS symbol disappears after a few seconds.

**Comment by breautek** [comment] 2020-01-04 16:54
The described behaviour really sounds like an environmental issue.

But here is a couple more tips...

I don't access to an iOS device at this moment, and I'm not very familiar with the iOS location settings, but ensure that high accuracy is enabled, or that wifi/cell towers for location tracking is enabled. Anything that is "GPS Only" will take a very long time for devices to obtain a satellite fix (Generally this takes 10-15 minutes from a cold start). This is unfortunately a phone setting, not an app setting, so if this solves the problem, then there is very little you can do other than give appropriate error feedback to the user.

Another thing you can try is to remove the distance filter. I would recommend doing this only to ensure that you're not getting gps points filtered while debugging. It isn't recommended to keep it like this for most applications because it will cause battery drain, but might aid in debugging.

https://github.com/apache/cordova-plugin-geolocation/blob/6570cf9fd2c546620f6aa8b2a07cf0b8b073a95c/src/ios/CDVLocation.m#L144

You can temporarily modify this line to ensure that GPS isn't being filtered by distance travelled. Set `distanceFilter` to `kCLDistanceFilterNone` to disable the filter, so events will be triggered even if the user hasn't moved a significant distance.

Lastly, if the issue persists, I would recommend creating a basic barebones sample app with the minimum requirements to reproduce the issue. So for example, a pure cordova with only the `cordova-plugin-geolocation` installed, but not ionic, or any other framework. This is to help isolate the issue away from frameworks and prove that the issue lies inside Cordova.

**Comment by jpangburn** [comment] 2020-09-29 16:08
I can confirm @breautek 's comment.  The problem you are likely experiencing is the distanceFilter.  If you move less than 5 meters, you won't get an update.  While this is probably great for driving apps, for apps on foot where you're trying to store a reasonably precise point it won't really work for you.  I imagine the people reporting this are not moving far when reporting "it stops after 2-5 seconds", this is the time when the GPS is locating you and precision is increasing.  Once it has good precision, you won't get more updates until you move more than 5 meters.

Fixing the line as he says resolves the problem.  You can put `0` or `kCLDistanceFilterNone`.  You'll get updates, in my testing, if the device moves even half a foot.

**Comment by breautek** [comment] 2023-06-05 01:48
Closing as stale

**Closed by breautek** 2023-06-05 01:48 UTC
Labels: support, platform: ios
